project:
  type: website
  output-dir: docs

website:
  title: "NN"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/krasing/nn
      - icon: twitter
        href: https://twitter.com/gkrasin
format:
  html:
    theme: litera
    css: styles.css



