project:
  type: website
  output-dir: docs

website:
  title: "NN"
  site-url: "https://krasing.github.io/nn/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/krasing/nn
      - icon: twitter
        href: https://twitter.com/gkrasin
      - icon: rss
        href: https://krasing.github.io/nn/index.xml
format:
  html:
    theme: litera
    css: styles.css



